try{
    console.log("Hello");
    console.log(a);
    console.log("ending try");
}
catch(err){
    console.log("Handled",err);
}
finally{
    console.log("Finally")
}
console.log("End");